# Generated by Django 5.1.1 on 2024-09-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_avatar_link_employee_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='avatar_link',
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
